### ISSUE TITLE
Parsing Quality line variability

### ISSUE THREAD

**Issue by stevepacker** [tlhunter/node-wireless#31]
In the Quality line, I've seen a couple of different formats, both which break the regex parser in `Wireless.prototype._parseScan` (the first line breaks because it's a 3-digit number):

    Quality=100/100  Signal level=47/100
    Quality=66/100  Signal level=52/100
    Quality=58/100  Signal level=80/100
    Quality=61/100  Signal level=72/100
    Quality:23  Signal level:0  Noise level:0
    Quality:93  Signal level:0  Noise level:0
    Quality:13  Signal level:0  Noise level:0

This was seen on Raspbian (Raspberry Pi):
- iwconfig: Wireless-Tools version 30
- iw: version 3.4
- /etc/debian_version: 7.6
- uname -r: 3.12.28+
- uname -m: armv6l

**Comment by alepee** [comment]
+1, raspberry pi output looks like

````
Cell 01 - Address: 04:A1:51:10:18:10
          ESSID:"Polabox"
          Protocol:IEEE 802.11bgn
          Mode:Master
          Frequency:2.437 GHz (Channel 6)
          Encryption key:on
          Bit Rates:72 Mb/s
          Extra:rsn_ie=30140100000fac040100000fac040100000fac020c00
          IE: IEEE 802.11i/WPA2 Version 1
              Group Cipher : CCMP
              Pairwise Ciphers (1) : CCMP
              Authentication Suites (1) : PSK
          IE: Unknown: DD7F0050F204104A00011010440001021041000100103B0001031047001072692C304518D97351F439B5DF9FC8131021000D4E4554474541522C20496E632E10230009574E5231303030763310240009574E523130303076331042000538333235381054000800060050F204000110110009574E52313030307633100800020084
          Quality=100/100  Signal level=95/100  
````

node-wireless currently check for `Quality=xx/70` and cause match to be `null`
